spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false

logging:
  level:
    com.family: DEBUG
    org.springframework.security: DEBUG
