spring:
  flyway:
    clean-disabled: false

logging:
  level:
    com.family: DEBUG
    com.family.auth.mapper: TRACE
    com.family.device.mapper: TRACE
    com.family.member.mapper: TRACE
    com.family.permission.mapper: TRACE
    org.springframework.security: DEBUG
